- alias: WLED outside - ON evening
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"

  action:
    service: light.turn_on
    entity_id: light.outside

- alias: WLED outside - OFF evening
  trigger:
    platform: time
    at: "23:30:00"

  action:
    service: light.turn_off
    entity_id: light.outside

- alias: WLED outside - ON morning
  trigger:
    platform: time
    at: "06:00:00"

  action:
    service: light.turn_on
    entity_id: light.outside

- alias: WLED outside - OFF morning
  trigger:
    platform: sun
    event: sunrise
    offset: "00:45:00"

  action:
    service: light.turn_off
    entity_id: light.outside


- alias: Deurbel - WLED outside
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell
      to: "on"

  condition:
    condition: state
    entity_id: light.outside
    state: "on"
  action:
    - data:
        scene_id: doorbell_wled_revert
        snapshot_entities: 'light.outside'
      service: scene.create
    - data:
        brightness: 255
        entity_id: light.outside
      service: light.turn_on
    - data:
        effect: 'Colorloop'
        speed: 225
      entity_id: light.outside
      service: wled.effect
    - delay: 00:00:15
    - data:
        entity_id: scene.doorbell_wled_revert
      service: scene.turn_on
