- alias: Deurbel - Entree
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_door_mailbox_contact
      to: "on"

  condition:
    - condition: template
      value_template: "{{((as_timestamp(now()) - as_timestamp(states.automation.deurbel_entree.attributes.last_triggered)) / 60) | int > 2 }}"

  action:
    - service: shell_command.doorbell_snapshot
    - service: notify.all_devices
      data:
        title: "Ding dong!"
        message: "Er is iemand aan de deur"
        data:
          image: "https://home.ashwinvandijk.nl/local/doorbell.jpg"
          attachment:
            url: "https://home.ashwinvandijk.nl/local/doorbell.jpg"
            content-type: jpeg
            hide-thumbnail: false

