- alias: Deurbel - Entree
  trigger:
    - platform: state
      entity_id: binary_sensor.deurbel
      to: "on"

  condition:
    - condition: template
      value_template: "{{((as_timestamp(now()) - as_timestamp(states.automation.deurbel_entree.attributes.last_triggered)) / 60) | int > 2 }}"

  action:
    - service: camera.snapshot
      data:
        entity_id: camera.dahua_mediaprofile_channel1_substream1
        filename: /config/www/doorbell.jpg
    - service: notify.all_devices
      data:
        title: "Ding dong!"
        message: "Er is iemand aan de deur"
        data:
          image: "https://home.ashwinvandijk.nl/local/doorbell.jpg"
          attachment:
            url: "https://home.ashwinvandijk.nl/local/doorbell.jpg"
            content-type: jpeg
            hide-thumbnail: false

