- alias: Verlichting - Entree - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_6_contact, input_boolean.entrance_presence
      to: "on"

  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: "Normaal"

  action:
    - service: homeassistant.turn_on
      entity_id: light.zigbee_e14_2_light
      data:
        brightness_pct: 100

- alias: Verlichting - Entree - Aan (Nacht)
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_6_contact, input_boolean.entrance_presence
      to: "on"

  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: "Nacht"

  action:
    - service: homeassistant.turn_on
      entity_id: light.zigbee_e14_2_light
      data:
        brightness_pct: 60

- alias: Verlichting - Entree - Standby
  trigger:
    - platform: state
      entity_id: input_boolean.entrance_presence
      to: "off"

  action:
    - service: homeassistant.turn_on
      entity_id: light.zigbee_e14_2_light
      data:
        brightness_pct: 30
        transition: 30

- alias: Verlichting - Entree - Uit
  trigger:
    - platform: state
      entity_id: input_boolean.entrance_presence
      to: "off"
      for:
        minutes: 2

  action:
    - service: light.turn_off
      entity_id: light.zigbee_e14_2_light
      data:
        transition: 30
