- alias: Brievenbus - Entree
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_mailbox_contact
      from: "off"
      to: "on"

  condition:
    - condition: template
      value_template: "{{((as_timestamp(now()) - as_timestamp(states.automation.brievenbus_entree.attributes.last_triggered)) / 60) | int > 1 }}"

  action:
    - service: camera.snapshot
      data:
        entity_id: camera.dahua_mediaprofile_channel1_substream1
        filename: /config/www/doorbell.jpg
    - service: notify.all_devices
      data:
        message: "Er is post!"
        data:
          image: "https://home.ashwinvandijk.nl/local/doorbell.jpg"
          attachment:
            url: "https://home.ashwinvandijk.nl/local/doorbell.jpg"
            content-type: jpeg
