- alias: Brievenbus - Entree
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_4_contact
      to: "on"

  action:
    service: notify.mobile_app_ashwiphone
    data:
      message: "Er is post!"
