- alias: Aanwezigheid - Entree - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_6_contact, binary_sensor.zigbee_occupancy_3_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.entrance_presence

- alias: Aanwezigheid - Entree - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_occupancy_3_occupancy
    to: "off"
    for:
      minutes: 1

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.entrance_presence
