- alias: Aanwezigheid - Entree - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.binary_sensor.zigbee_door_entrance_contact
        - binary_sensor.zigbee_sensor_entrance_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.entrance_presence

- alias: Aanwezigheid - Entree - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_sensor_entrance_occupancy
    to: "off"
    for:
      minutes: 2

  condition:
    - condition: state
      entity_id: binary_sensor.binary_sensor.zigbee_door_entrance_contact
      state: "off"

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.entrance_presence
