- alias: Aanwezigheid - Entree - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_6_contact, group.entrance_presence
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.entrance_presence

- alias: Aanwezigheid - Entree - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_contact_6_contact
    to: "off"
    for:
      minutes: 2

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.entrance_presence
