- platform: template
  sensors:
    livingroom_media_on:
      value_template: >-
        {{ states('sensor.livingroom_remote') != "PowerOff" }}

    livingroom_tv_on:
      value_template: >-
        {{ states('sensor.livingroom_remote') == "TV" or states('sensor.livingroom_remote') == "PS4" or states('sensor.livingroom_remote') == "Chromecast" }}

    livingroom_dark:
      value_template: >-
        {{ states('sensor.livingroom_dark') | float < 35 }}
