- platform: template
  sensors:
    livingroom_media_on:
      value_template: >-
        {{ states('sensor.livingroom_remote') != "PowerOff" }}

    livingroom_tv_on:
      value_template: >-
        {{ states('media_player.chromecast_livingroom') == 'playing' and state_attr('media_player.chromecast_livingroom', 'media_content_type') == "movie" }}

    livingroom_dark:
      value_template: >-
        {{ states('sensor.livingroom_dark') | float < 25 }}
