- platform: template
  sensors:
    livingroom_media_on:
      value_template: >-
        {{ states('remote.livingroom') != PowerOff }}

    livingroom_dark:
      value_template: >-
        {{ states('sensor.livingroom_dark') | float < 40 }}
