- platform: template
  sensors:
    is_night:
      value_template: >-
        {{ states('input_select.house_mode') == 'Nacht' }}

    livingroom_tv_on:
      value_template: >-
        {{ states('media_player.chromecast_livingroom') == 'playing' and (state_attr('media_player.chromecast_livingroom', 'media_content_type') == "movie" or state_attr('media_player.chromecast_livingroom', 'media_content_type') == "tvshow") }}

    livingroom_dark:
      value_template: >-
        {{ states('sensor.presence_sensor_fp2_4947_light_sensor_light_level') | float < 190 }}
