homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  # themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
 base_url: !secret base_url
 use_x_forwarded_for: true
 trusted_proxies:
   - 172.17.0.0/20


sensor:
  - platform: foxess
    username: !secret foxesscloud_username
    password: !secret foxesscloud_password
    deviceID: !secret foxesscloud_inverter_id

# Discover some devices automatically
discovery:
  ignore:
    - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
#cloud:

# mobile_app:

system_health:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

person:
  - name: Ashwin
    id: ashwin
    user_id: 8de1646184bb444fba567e084ba52b77
    device_trackers:
      - device_tracker.ashwiphone

mqtt:
  broker: 10.10.1.1
  port: 1883
  client_id: homeassistant
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

recorder:
  purge_keep_days: 14
  db_url: !secret recorder_url

#hue:
#  bridges:
#    - host: 10.10.1.3

stream:

cast:
  media_player:

python_script:

remote:
  - platform: harmony
    name: Livingroom
    host: 10.10.1.10

lovelace:
  mode: yaml
  resources:
    - url: /local/community/simple-thermostat/simple-thermostat.js
      type: module
    - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/community/vacuum-card/vacuum-card.js
      type: module

    - url: /local/mini-media-player-bundle.js
      type: js
    - url: /local/group-card.js
      type: js
    - url: /local/community/simple-thermostat.js
      type: module
    - url: /local/button-card.js
      type: module
    - url: /local/bignumber-card.js
      type: module
    - url: /local/vertical-style-card.js
      type: module

hisense_aehw4a1:
  ip_address:
    - 10.10.1.6
    - 10.10.1.7

homekit:
  filter:
    include_entities:
      - light.shelly_dimmer_bedroom_sink
      - input_boolean.homekit_livingroom
      - light.hallway_upstairs
  entity_config:
    light.shelly_dimmer_bedroom_sink:
      name: Wastafel
    input_boolean.homekit_livingroom:
      name: Woonkamer
    light.hallway_upstairs:
      name: Gang

google_assistant:
  project_id: secret-index-265114
  service_account: !include google.json
  report_state: true
  exposed_domains:
    - switch
    - light
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

tado:
  username: !secret tado_user
  password: !secret tado_password

emulated_roku:
  servers:
    - name: HASS
      listen_port: 8060
      host_ip: 10.10.1.1

shelly:
  discover_by_ip:
    - '10.10.1.135'
    - '10.10.1.136'
    - '10.10.1.137'
    - '10.10.1.138'
    - '10.10.1.139'

vacuum:
  - platform: xiaomi_miio
    name: s5max
    host: 10.10.1.9
    token: !secret roborock_token



automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
climate: !include_dir_merge_list climate
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_datetime: !include_dir_merge_named input_datetime
input_number: !include_dir_merge_named input_number
input_select: !include_dir_merge_named input_select
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
# mqtt: !include_dir_merge_list mqtt
sensor: !include_dir_merge_list sensor
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
zone: !include_dir_merge_list zone

mqtt:
  light:
    - name: kitchen
      command_topic: "zigbee2mqtt/kitchen_light/set"
      state_topic: "zigbee2mqtt/kitchen_light/set"
      brightness: true
      schema: json

    - name: hallway_upstairs
      command_topic: "zigbee2mqtt/hallway_upstairs_light/set"
      state_topic: "zigbee2mqtt/hallway_upstairs_light/set"
      brightness: true
      schema: json
  
  binary_sensor:
    - name: "Doorbell"
      state_topic: 'DahuaVTO/BackKeyLight/Event'
      value_template: '{{ value_json.Data.State }}'
      payload_on: "1"
      payload_off: "0"


rest_command:
  tado_home:
    url: !secret tado_geo_url
    method: PUT
    headers:
      accept: "application/json, text/html"
    payload: '{"geolocation":{"latitude":51.942821, "longitude": 4.472988 },"timestamp":"{{ now().isoformat() }}","accuracy":32}'
    content_type: "application/json; charset=utf-8"

  tado_away:
    url: !secret tado_geo_url
    method: PUT
    headers:
      accept: "application/json, text/html"
    payload: '{"geolocation":{"latitude": 24.626895, "longitude": -77.938657 },"timestamp":"{{ now().isoformat() }}","accuracy":32}'
    content_type: "application/json; charset=utf-8"

  rhasspy_speak_hallway_upstairs:
      url: 'http://10.10.1.16:12101/api/text-to-speech'
      method: 'POST'
      payload: 'De wasmachine is klaar'
      headers:
        content-type: 'text/plain'

notify:
  - name: all_devices
    platform: group
    services:
      - service: mobile_app_ashwiphone
      - service: mobile_app_sm_g981b

intent:

intent_script:
  SetLightOn:
    speech:
      text: '{{ ["OK, ik heb het licht in de " ~ room + " aangezet.", "OK, het licht in de " ~ room + " is aan.", "Uiteraard! Ik heb het licht aangezet.", "Klaar", "OK, het licht is aan"] | random }}'
    action:
      - service_template: 'script.turn_on'
        data_template:
          entity_id: 'script.speech_{{ room }}_lights_on'

  SetLightOff:
    speech:
      text: '{{ ["OK, ik heb het licht in de " ~ room + " uitgezet.", "OK, het licht in de " ~ room + " is uit.", "Uiteraard", "Klaar", "OK, het licht is uit"] | random }}'

    action:
      - service_template: 'script.turn_on'
        data_template:
          entity_id: 'script.speech_{{ room }}_lights_off'

  LeaveHouse:
    speech:
      text: '{{ ["OK, de groeten aan je voeten!", "Tot later!", "Tot ziens!", "OK, doei!", "Dag"] | random }}'

