homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include_dir_merge_named customize

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
#cloud:

# mobile_app:

system_health:

person:
  - name: Ashwin
    id: ashwin
    user_id: 8de1646184bb444fba567e084ba52b77
    device_trackers:
      - device_tracker.ashwiphone

mqtt:
  broker: 10.10.1.1
  port: 1883
  client_id: homeassistant
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

recorder:
  purge_interval: 2
  purge_keep_days: 4
  db_url: !secret recorder_url

hue:
  bridges:
    - host: 10.10.1.3

camera:
  - platform: generic
    name: Voordeur
    still_image_url: 10.10.1.4:554/cam/realmonitor?channel=1&subtype=1
    stream_source: 10.10.1.4:554/cam/realmonitor?channel=1&subtype=1
    username: !secret camera1_username
    password: !secret camera1_password

cast:
  media_player:
    - host: 10.10.1.11
    - host: 10.10.1.12

remote:
  - platform: harmony
    name: Livingroom
    host: 10.10.1.10

lovelace:
  mode: yaml

homekit:
  filter:
    include_entities:
      - input_boolean.homekit_livingroom
      - light.wifi_e27cwww_02
      - light.zigbee_e27c_3_light
      - light.bedroom_sink
      - switch.sonoff_02
      - input_boolean.bedroom_in_bed
  entity_config:
    light.bedroom_sink:
      name: Wastafel
    light.zigbee_e27c_3_light:
      name: Groot
    input_boolean.homekit_livingroom:
      name: Woonkamer
    light.wifi_e27cwww_02:
      name: Lamp op het kastje
    switch.sonoff_02:
      name: Gang
    input_boolean.bedroom_in_bed:
      name: In bed

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 300

tado:
  username: !secret tado_user
  password: !secret tado_password

emulated_roku:
  servers:
    - name: HASS
      listen_port: 8060
      host_ip: 10.10.1.1

automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_datetime: !include_dir_merge_named input_datetime
input_select: !include_dir_merge_named input_select
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
sensor: !include_dir_merge_list sensor
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
zone: !include_dir_merge_list zone

rest_command:
  tado_home:
    url: !secret tado_geo_url
    method: PUT
    headers:
      accept: "application/json, text/html"
    payload: '{"geolocation":{"latitude":51.942821, "longitude": 4.472988 },"timestamp":"{{ now().isoformat() }}","accuracy":32}'
    content_type: "application/json; charset=utf-8"

  tado_away:
    url: !secret tado_geo_url
    method: PUT
    headers:
      accept: "application/json, text/html"
    payload: '{"geolocation":{"latitude": 24.626895, "longitude": -77.938657 },"timestamp":"{{ now().isoformat() }}","accuracy":32}'
    content_type: "application/json; charset=utf-8"

webhook:

zigbee2mqtt_networkmap:
  topic: zigbee

panel_iframe:
  networkmap:
    title: "Zigbee Map"
    url: "/local/community/zigbee2mqtt_networkmap/map.html"
    icon: "mdi:graphql"
