homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  # themes: !include themes.yaml

# Enables configuration UI
config:


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 http:
   base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
#cloud:

# mobile_app:

system_health:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

person:
  - name: Ashwin
    id: ashwin
    user_id: 8de1646184bb444fba567e084ba52b77
    device_trackers:
      - device_tracker.ashwiphone

mqtt:
  broker: 10.10.1.1
  port: 1883
  client_id: homeassistant
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

recorder:
  purge_keep_days: 4
  db_url: !secret recorder_url

hue:
  bridges:
    - host: 10.10.1.3

stream:

camera:
  - platform: generic
    name: Voordeur
    still_image_url: !secret camera1_stream
    stream_source: !secret camera1_stream

cast:
  media_player:
    - host: 10.10.1.11
    - host: 10.10.1.12

remote:
  - platform: harmony
    name: Livingroom
    host: 10.10.1.10

lovelace:
  mode: yaml
  resources:
    - url: /local/community/simple-thermostat/simple-thermostat.js
      type: module
    - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module

    - url: /local/mini-media-player-bundle.js
      type: js
    - url: /local/group-card.js
      type: js
    - url: /local/community/simple-thermostat.js
      type: module
    - url: /local/button-card.js
      type: module
    - url: /local/bignumber-card.js
      type: module
    - url: /local/vertical-style-card.js
      type: module

homekit:
  filter:
    include_entities:
      - light.bedroom_sink
      - input_boolean.homekit_livingroom
      - switch.plug_hallway_upstairs_switch
  entity_config:
    light.bedroom_sink:
      name: Wastafel
    input_boolean.homekit_livingroom:
      name: Woonkamer
    switch.plug_hallway_upstairs_switch:
      name: Gang

tado:
  username: !secret tado_user
  password: !secret tado_password

emulated_roku:
  servers:
    - name: HASS
      listen_port: 8060
      host_ip: 10.10.1.1

shelly:
  sensors:
    - 'switch'
  discover_by_ip:
    - '10.10.1.135'
    - '10.10.1.136'
    - '10.10.1.137'
    - '10.10.1.138'

automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
climate: !include_dir_merge_list climate
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_datetime: !include_dir_merge_named input_datetime
input_number: !include_dir_merge_named input_number
input_select: !include_dir_merge_named input_select
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
sensor: !include_dir_merge_list sensor
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
zone: !include_dir_merge_list zone

rest_command:
  tado_home:
    url: !secret tado_geo_url
    method: PUT
    headers:
      accept: "application/json, text/html"
    payload: '{"geolocation":{"latitude":51.942821, "longitude": 4.472988 },"timestamp":"{{ now().isoformat() }}","accuracy":32}'
    content_type: "application/json; charset=utf-8"

  tado_away:
    url: !secret tado_geo_url
    method: PUT
    headers:
      accept: "application/json, text/html"
    payload: '{"geolocation":{"latitude": 24.626895, "longitude": -77.938657 },"timestamp":"{{ now().isoformat() }}","accuracy":32}'
    content_type: "application/json; charset=utf-8"

  rhasspy_speak_hallway_upstairs:
      url: 'http://10.10.1.16:12101/api/text-to-speech'
      method: 'POST'
      payload: 'De wasmachine is klaar'
      headers:
        content-type: 'text/plain'


shell_command:
  doorbell_snapshot: !secret shell_doorbell_snapshot

notify:
  - name: all_devices
    platform: group
    services:
      - service: mobile_app_ashwiphone
      - service: mobile_app_sm_g960f

intent:

intent_script:
  SetLightOn:
    speech:
      text: '{{ ["OK, ik heb het licht in de " ~ name + " aangezet.", "OK, het licht in de {{ room }} is aan.", "Uiteraard", "Klaar", "Oke"] | random }}'
    action:
      - service_template: 'script.turn_on'
        data_template:
          entity_id: 'script.speech_{{ room }}_lights_on'

  SetLightOff:
    speech:
      text: '{{ ["OK, ik heb het licht in de {{ room }} uitgezet.", "OK, het licht in de {{ room }} is uit.", "Uiteraard", "Klaar", "Oke"] | random }}'

    action:
      - service_template: 'script.turn_on'
        data_template:
          entity_id: 'script.speech_{{ room }}_lights_on'

  LeaveHouse:
    speech:
      type: plain
      text: '{{ ["OK, de groeten aan je voeten!", "Tot later!", "Tot ziens!", "OK, doei!", "Dag hoor"] | random }}'

