views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: conditional
        conditions:
          - entity: media_player.spotify_ashwin_van_dijk
            state_not: "idle"
          - entity: media_player.spotify_ashwin_van_dijk
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.spotify_ashwin_van_dijk

      - type: conditional
        conditions:
          - entity: media_player.spotify_kim_vermeer
            state_not: "idle"
          - entity: media_player.spotify_kim_vermeer
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.spotify_kim_vermeer



      - type: entities
        title: MultiRoom
        show_header_toggle: false

        entities:
          - type: section

          - type: custom:mini-media-player
            entity: media_player.snapcast_group_all
            source: full
            group: true
            name: Bron
            hide:
              icon: true
              power: true
              controls: true
              volume: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_woonkamer
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_woonkamer_2
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_keuken
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_slaapkamer
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_hal
            group: true
            hide:
              power: true
              controls: true
              source: true

      - type: entities
        title: Woonkamer
        show_header_toggle: false
        entities:
          - type: section

          - entity: climate.woonkamer

          - type: section

          - input_select.livingroom_scene
          - input_select.livingroom_remote

          - type: media-control
            entity: media_player.chromecast_livingroom
            group: true
            artwork: cover

          - type: section
            label: Rolgordijnen

          - type: custom:slider-entity-row
            entity: cover.blind_01
            toggle: true

          - type: section
            label: Verlichting

          - light.shelly_01

          - type: custom:slider-entity-row
            entity: light.zigbee_e14_3_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_1_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_2_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_3_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.wifi_e27cwww_02
            toggle: true

          - type: custom:slider-entity-row
            entity: light.shelly_dimmer_02
            toggle: true

          - type: custom:slider-entity-row
            entity: light.gu10_erker
            toggle: true

      - type: entities
        title: Keuken
        show_header_toggle: false
        entities:
          - type: section

          - type: custom:slider-entity-row
            entity: light.kitchen
            toggle: true

      - type: entities
        title: Badkamer
        show_header_toggle: false
        entities:
          - type: section
          - entity: climate.badkamer

          - type: section
          - light.shelly_04

      - type: entities
        title: Entree
        show_header_toggle: false
        entities:
          - type: section
            label: Verlichting
          - type: custom:slider-entity-row
            entity: light.zigbee_e14_2_light
            toggle: true

      - type: entities
        title: Gang
        show_header_toggle: false

        entities:
          - type: section

          - switch.plug_06

      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_4_light
            toggle: true


      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Werkkamer
          - type: custom:simple-thermostat
            entity: climate.werkkamer
            step_layout: row
            step_size: 1
            name: false
            icon: false
            control: false


          - type: thermostat
            entity: climate.airco_werkkamer

          - type: entities
            show_header_toggle: false
            entities:
              - switch.plug_02

              - type: section
                label: Verlichting

              - type: custom:slider-entity-row
                entity: light.shelly_dimmer_01
                toggle: true

      #      - type: entities
      #        title: Werkkamer
      #        show_header_toggle: false
      #
      #        entities:
      #          - type: section
      #          - entity: climate.werkkamer
      #
      #          - type: section
      #            label: Verlichting
      #
      #          - type: custom:slider-entity-row
      #            entity: light.zigbee_e14_2_light
      #            toggle: true

      - type: entities
        title: Slaapkamer
        show_header_toggle: false

        entities:
          - type: section

          - entity: climate.slaapkamer

          - type: media-control
            entity: media_player.chromecast_bedroom
            group: true
            artwork: cover

          - type: section
            label: Verlichting

          - light.shelly_02

          - type: custom:slider-entity-row
            entity: light.bedroom_sink
            toggle: true


  - !include lovelace/livingroom.yaml

  - !include lovelace/workroom.yaml

  - title: SensorenOld
    icon: mdi:cogs
    cards:
      - type: entities
        title: Huis
        show_header_toggle: false
        entities:
          - input_select.house_mode
          - input_boolean.house_vacation

      #      - type: custom:group-card
      #        card:
      #          type: entities
      #          title: Woonkamer
      #          show_header_toggle: false
      #        group: group.sensors_livingroom

      - type: entities
        title: Keuken
        show_header_toggle: false
        entities:
          - type: section

          - input_boolean.kitchen_presence
          - binary_sensor.zigbee_occupancy_1_occupancy
          - sensor.zigbee_occupancy_1_illuminance
          - sensor.plug_01_power
          - sensor.zigbee_climate_3_temperature
          - sensor.zigbee_climate_3_humidity
          - sensor.zigbee_climate_3_pressure
          - sensor.zigbee_climate_2_temperature

      - type: custom:group-card
        card:
          type: entities
          title: Badkamer
          show_header_toggle: false
        group: group.sensors_bathroom


      - type: entities
        title: Werkkamer
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.workroom_presence
          - binary_sensor.sensor_workroom_occupancy
          - sensor.occupancy_workroom_illuminance

      - type: custom:group-card
        card:
          type: entities
          title: Entree
          show_header_toggle: false
        group: group.sensors_entrance

      - type: entities
        title: Gang (boven)
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.hallway_upstairs_presence
          - sensor.zigbee_occupancy_7_illuminance
          - binary_sensor.zigbee_occupancy_7_occupancy

      - type: entities
        title: Slaapkamer
        show_header_toggle: false
        entities:
          - type: section

          - input_boolean.bedroom_presence
          - binary_sensor.zigbee_occupancy_6_occupancy
          - binary_sensor.zigbee_contact_2_contact
          - sensor.zigbee_climate_1_temperature
          - sensor.zigbee_climate_1_humidity
          - sensor.zigbee_climate_1_pressure

      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section

          - input_boolean.washroom_presence
          - binary_sensor.zigbee_contact_3_contact
          - sensor.plug_05_power
          - sensor.plug_03_power

  - title: Apparaten
    icon: mdi:washing-machine

    cards:
      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section
            label: Wasmachine

          - input_select.washingmachine_status
          - sensor.washingmachine_on_time
          - sensor.plug_05_power

          - type: section
            label: Droger

          - input_select.tumbledryer_status
          - sensor.tumbledryer_on_time
          - sensor.plug_03_power

      - type: entities
        title: Keuken
        show_header_toggle: false
        entities:
          - type: section
            label: Status

          - input_select.dishwasher_status

          - type: section
            label: Verbruik

          - sensor.plug_01_power
