resources:
  - url: /local/waze-card.js?v=2.0.0
    type: js
  - url: /local/mini-media-player-bundle.js
    type: js
  - url: /local/slider-entity-row.js
    type: js

views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: custom:waze-card
        entities:
          - entity: sensor.ashwin_s_huis_naar_hbr
            zone: zone.hbr
            name: Ashwin's huis naar HBR
          - entity: sensor.hbr_naar_ashwin_s_huis
            zone: zone.home
            name: HBR naar Ashwin's huis

      - type: entities
        title: Woonkamer
        show_header_toggle: false
        entities:
          - input_select.livingroom_scene
          - input_select.livingroom_remote

          - type: custom:mini-media-player
            entity: media_player.chromecast_livingroom

          - type: section
            label: Verlichting

          - light.shelly_01

          - type: custom:slider-entity-row
            entity: light.zigbee_e14_1_light

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_2_light

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_3_light

          - switch.sonoff_01
          - switch.sonoff_03
