resources:
  - url: /local/waze-card.js?v=2.0.0
    type: js
  - url: /local/mini-media-player-bundle.js
    type: js
  - url: /local/slider-entity-row.js
    type: js
  - url: /local/group-card.js
    type: js
  - url: /local/simple-thermostat.js
    type: module

views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: entities
        title: MultiRoom
        show_header_toggle: false

        entities:
          - type: custom:mini-media-player
            entity: media_player.snapcast_group_all
            source: full
            group: true
            name: Bron
            hide:
              icon: true
              power: true
              controls: true
              volume: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_woonkamer
            group: true
            hide:
              power: true
              controls: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_keuken
            group: true
            hide:
              power: true
              controls: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_slaapkamer
            group: true
            hide:
              power: true
              controls: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_hal
            group: true
            hide:
              power: true
              controls: true

      - type: custom:mini-media-player
        entity: media_player.spotify
        artwork: cover
        hide_when_off: true
        hide:
          volume: true
          power: true

      - type: entities
        title: Woonkamer
        show_header_toggle: false
        entities:
          - type: section

          - entity: climate.woonkamer

          - type: section

          - input_select.livingroom_scene
          - input_select.livingroom_remote

          - type: custom:mini-media-player
            entity: media_player.chromecast_livingroom
            group: true
            artwork: cover

          - type: section
            label: Verlichting

          - light.shelly_01

          - type: custom:slider-entity-row
            entity: light.zigbee_e14_1_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_1_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_2_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_3_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.wifi_e27cwww_02
            toggle: true

          - switch.sonoff_03

      - type: entities
        title: Keuken
        show_header_toggle: false
        entities:
          - type: section

          - type: custom:slider-entity-row
            entity: light.kitchen
            toggle: true

      - type: entities
        title: Badkamer
        show_header_toggle: false
        entities:
          - type: section

          - light.shelly_04

      - type: entities
        title: Entree
        show_header_toggle: false
        entities:
          - type: section

          - light.wifi_e27cwww_01

      - type: entities
        title: Gang
        show_header_toggle: false

        entities:
          - type: section

          - switch.sonoff_02

      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_4_light
            toggle: true

      - type: entities
        title: Slaapkamer
        show_header_toggle: false

        entities:
          - type: section

          - entity: climate.slaapkamer

          - type: custom:mini-media-player
            entity: media_player.chromecast_bedroom
            group: true
            artwork: cover

          - type: section
            label: Verlichting

          - light.shelly_05

          - type: custom:slider-entity-row
            entity: light.bedroom_sink
            toggle: true

  - title: Sensoren
    icon: mdi:cogs
    cards:
      - type: entities
        title: Huis
        show_header_toggle: false
        entities:
          - input_select.house_mode

      - type: custom:group-card
        card:
          type: entities
          title: Woonkamer
          show_header_toggle: false
        group: group.sensors_livingroom

      - type: custom:group-card
        card:
          type: entities
          title: Keuken
          show_header_toggle: false
        group: group.sensors_kitchen

      - type: custom:group-card
        card:
          type: entities
          title: Badkamer
          show_header_toggle: false
        group: group.sensors_bathroom

      - type: custom:group-card
        card:
          type: entities
          title: Entree
          show_header_toggle: false
        group: group.sensors_entrance

      - type: custom:group-card
        card:
          type: entities
          title: Gang (boven)
          show_header_toggle: false
        group: group.sensors_hallway_upstairs

      - type: custom:group-card
        card:
          type: entities
          title: Slaapkamer
          show_header_toggle: false
        group: group.sensors_bedroom

      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section

          - input_boolean.washroom_presence
          - binary_sensor.zigbee_contact_3_contact
          - sensor.plug_02_power
