resources:
  - url: /local/waze-card.js?v=2.0.0
    type: js
  - url: /local/mini-media-player-bundle.js
    type: js
  - url: /local/slider-entity-row.js
    type: js

views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: entities
        title: Woonkamer
        show_header_toggle: false
        entities:
          - input_select.livingroom_scene
          - input_select.livingroom_remote

          - type: custom:mini-media-player
            entity: media_player.chromecast_livingroom

          - type: section
            label: Verlichting

          - light.shelly_01

          - type: custom:slider-entity-row
            entity: light.zigbee_e14_1_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_2_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_3_light
            toggle: true

          - switch.sonoff_01
          - switch.sonoff_03

      - type: entities
        title: Keuken
        show_header_toggle: false
        entities:
          - type: section
            label: Verlichting

          - type: custom:slider-entity-row
            entity: light.kitchen
            toggle: true

      - type: entities
        title: Badkamer
        show_header_toggle: false
        entities:
          - type: section
            label: Verlichting

          - light.shelly_04

      - type: entities
        title: Gang
        show_header_toggle: false

        entities:
          - type: section
            label: Verlichting

          - switch.sonoff_02

      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section
            label: Verlichting

          - type: custom:slider-entity-row
            entity: light.zigbee_e27c_4_light
            toggle: true

      - type: entities
        title: Slaapkamer
        show_header_toggle: false

        entities:
          - type: section
            label: Verlichting

          - light.shelly_02

          - type: custom:slider-entity-row
            entity: light.bedroom_sink
            toggle: true

  - title: Sensoren
    icon: mdi:cogs
    cards:
      - type: entities
        title: Woonkamer
        show_header_toggle: false
        entities:
          - group.sensors_livingroom
