views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: conditional
        conditions:
          - entity: media_player.spotify_ashwin_van_dijk
            state_not: "idle"
          - entity: media_player.spotify_ashwin_van_dijk
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.spotify_ashwin_van_dijk

      - type: conditional
        conditions:
          - entity: media_player.spotify_kim_vermeer
            state_not: "idle"
          - entity: media_player.spotify_kim_vermeer
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.spotify_kim_vermeer



      - type: entities
        title: MultiRoom
        show_header_toggle: false

        entities:
          - type: section

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_woonkamer
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_woonkamer_2
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_keuken
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_badkamer
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_slaapkamer
            group: true
            hide:
              power: true
              controls: true
              source: true

          - type: custom:mini-media-player
            entity: media_player.snapcast_client_hal
            group: true
            hide:
              power: true
              controls: true
              source: true

      - type: entities
        title: Woonkamer
        show_header_toggle: false
        entities:
          - type: section

          - entity: climate.woonkamer

          - type: section

          - input_select.livingroom_scene
          - input_select.livingroom_remote

          -  media_player.chromecast_livingroom

          - type: section
            label: Rolgordijnen

          - cover.blind_01
          - cover.blind_02
          - cover.blind_03
          - cover.blind_04
          - cover.blind_05

          - type: section
            label: Vensterbanken

          - light.window_sill_01
          - light.window_sill_02
          - light.window_sill_03
          - light.window_sill_04

          - type: section
            label: Verlichting

          - light.shelly_01

          - type: custom:slider-entity-row
            entity: light.zigbee_tv_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_livingroom_corner_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_livingroom_window_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.zigbee_livingroom_big_light
            toggle: true

          - type: custom:slider-entity-row
            entity: light.wifi_e27cwww_02
            toggle: true

          - type: custom:slider-entity-row
            entity: light.shelly_dimmer_livingroom_standing
            toggle: true

          - type: custom:slider-entity-row
            entity: light.erker_gu10_cwww
            toggle: true

          - type: custom:slider-entity-row
            entity: light.closet
            toggle: true

      - type: entities
        title: Keuken
        show_header_toggle: false
        entities:
          - type: section

          - type: custom:slider-entity-row
            entity: light.kitchen
            toggle: true

      - type: entities
        title: Hal beneden
        show_header_toggle: false
        entities:
          - type: section

          - type: custom:slider-entity-row
            entity: light.shelly_dimmer_hallway_downstairs
            toggle: true

      - type: entities
        title: Badkamer
        show_header_toggle: false
        entities:
          - type: section
          - entity: climate.badkamer

          - type: section
          - type: custom:slider-entity-row
            entity: light.shelly_dimmer_bathroom
            toggle: true
          - light.shelly_04

      - type: entities
        title: Entree
        show_header_toggle: false
        entities:
          - type: section
            label: Verlichting
          - type: custom:slider-entity-row
            entity: light.zigbee_entrance_light
            toggle: true

      - type: entities
        title: Hal boven
        show_header_toggle: false

        entities:
          - type: section
          - light.shelly_terrace_lights
          - light.hallway_upstairs

      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section

          - type: custom:slider-entity-row
            entity: light.zigbee_washroom_light
            toggle: true


      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Werkkamer
          - type: custom:simple-thermostat
            entity: climate.werkkamer
            step_layout: row
            step_size: 1
            name: false
            icon: false
            control: false


          - type: thermostat
            entity: climate.airco_werkkamer

          - type: entities
            show_header_toggle: false
            entities:
              - switch.plug_workroom_speakers_switch

              - type: section
                label: Verlichting

              - type: custom:slider-entity-row
                entity: light.shelly_dimmer_workroom
                toggle: true

      #      - type: entities
      #        title: Werkkamer
      #        show_header_toggle: false
      #
      #        entities:
      #          - type: section
      #          - entity: climate.werkkamer
      #
      #          - type: section
      #            label: Verlichting
      #
      #          - type: custom:slider-entity-row
      #            entity: light.zigbee_entrance_light
      #            toggle: true

      - type: entities
        title: Slaapkamer
        show_header_toggle: false

        entities:
          - type: section

          - entity: climate.slaapkamer

          - media_player.chromecast_bedroom

          - type: section
            label: Verlichting

          - light.shelly_02

          - type: custom:slider-entity-row
            entity: light.shelly_dimmer_bedroom_sink
            toggle: true


  - !include lovelace/livingroom.yaml

  - !include lovelace/workroom.yaml

  - title: Sensoren
    icon: mdi:cogs
    cards:
      - type: entities
        title: Huis
        show_header_toggle: false
        entities:
          - input_select.house_mode
          - input_boolean.house_vacation

      - type: entities
        title: Woonkamer
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.livingroom_presence
          - binary_sensor.zigbee_sensor_livingroom_tv_occupancy
          - binary_sensor.zigbee_sensor_livingroom_fusebox_occupancy
          - binary_sensor.zigbee_sensor_livingroom_closet_occupancy
          - binary_sensor.zigbee_door_livingroom_contact

      - type: entities
        title: Inloopkast
        show_header_toggle: false
        entities:
          - type: section
          - binary_sensor.zigbee_sensor_closet_occupancy
          - sensor.zigbee_sensor_closet_illuminance

      - type: entities
        title: Keuken
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.kitchen_presence
          - binary_sensor.zigbee_sensor_kitchen_occupancy
          - sensor.zigbee_sensor_kitchen_illuminance

      - type: entities
        title: Badkamer
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.bathroom_presence
          - binary_sensor.multi_01_movement
          - binary_sensor.zigbee_door_bathroom_contact

      - type: entities
        title: Gang (beneden)
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.hallway_downstairs_presence
          - sensor.zigbee_sensor_hallway_downstairs_illuminance
          - binary_sensor.zigbee_sensor_hallway_downstairs_occupancy
          - binary_sensor.zigbee_sensor_hallway_downstairs_coatrack_occupancy

      - type: entities
        title: Werkkamer
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.workroom_presence
          - binary_sensor.zigbee_sensor_workroom_occupancy
          - sensor.zigbee_sensor_workroom_illuminance

      - type: entities
        title: Entree
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.entrance_presence
          - binary_sensor.zigbee_sensor_entrance_occupancy
          - binary_sensor.zigbee_door_entrance_contact

      - type: entities
        title: Gang (boven)
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.hallway_upstairs_presence
          - sensor.zigbee_sensor_hallway_upstairs_illuminance
          - binary_sensor.zigbee_sensor_hallway_upstairs_occupancy

      - type: entities
        title: Slaapkamer
        show_header_toggle: false
        entities:
          - type: section

          - input_boolean.bedroom_presence
          - binary_sensor.zigbee_sensor_bedroom_occupancy
          - binary_sensor.zigbee_door_bedroom_contact

      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section
          - input_boolean.washroom_presence
          - binary_sensor.zigbee_door_washroom_contact

  - title: Apparaten
    icon: mdi:washing-machine

    cards:
      - type: entities
        title: Washok
        show_header_toggle: false
        entities:
          - type: section
            label: Wasmachine

          - input_select.washingmachine_status
          - sensor.washingmachine_on_time
          - sensor.plug_washing_machine_power

          - type: section
            label: Droger

          - input_select.tumbledryer_status
          - sensor.tumbledryer_on_time
          - sensor.plug_tumble_dryer_power

      - type: entities
        title: Keuken
        show_header_toggle: false
        entities:
          - type: section
            label: Status

          - input_select.dishwasher_status

          - type: section
            label: Verbruik

          - sensor.plug_dishwasher_power

      - type: 'custom:vacuum-card'
        entity: vacuum.s5max
        stats:
          default:
            - attribute: filter_left
              unit: hours
              subtitle: Filter
            - attribute: side_brush_left
              unit: hours
              subtitle: Side brush
            - attribute: main_brush_left
              unit: hours
              subtitle: Main brush
            - attribute: sensor_dirty_left
              unit: hours
              subtitle: Sensors
          cleaning:
            - attribute: cleaned_area
              unit: m2
              subtitle: Cleaning area
            - attribute: cleaning_time
              unit: minutes
              subtitle: Cleaning time
