resources:
  - url: /local/waze-card.js?v=2.0.0
    type: js
  - url: /local/mini-media-player-bundle.js
    type: js
  - url: /local/slider-entity-row.js
    type: js

views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: custom:waze-card
        entities:
          - entity: sensor.ashwin_s_huis_naar_hbr
            zone: zone.hbr
            name: Ashwin's huis naar HBR
          - entity: sensor.hbr_naar_ashwin_s_huis
            zone: zone.home
            name: HBR naar Ashwin's huis

      - type: entities
        title: Woonkamer
        show_header_toggle: false
        entities:
          - input_number.slider

          - type: section
            label: Verlichting
          - type: custom:slider-entity-row
            entity: light.shelly_01

      - type: custom:mini-media-player
        entity: media_player.chromecast_livingroom
