- alias: Media - Bathroom - On
  initial: off
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_presence
      to: "on"

  action:
    - service: media_player.volume_set
      entity_id: media_player.snapcast_client_badkamer
      data:
        volume_level: 0.25

- alias: Media - Bathroom - Off
  initial: off
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_presence
      to: "off"
      for:
        minutes: 1

  action:
    - service: media_player.volume_set
      entity_id: media_player.snapcast_client_badkamer
      data:
        volume_level: 0.1
