- alias: Media - Bathroom - On
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_presence
      to: "on"

  action:
    - service: media_player.volume_mute
      entity_id: media_player.snapcast_client_badkamer
      data:
        is_volume_muted: false


- alias: Media - Bathroom - Off
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_presence
      to: "off"
      for:
        minutes: 1

  action:
    - service: media_player.volume_mute
      entity_id: media_player.snapcast_client_badkamer
      data:
        is_volume_muted: true
