- alias: Aanwezigheid - Badkamer - Aan
  initial_state: off
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_5_contact, binary_sensor.aeotec_zw100_multisensor_6_sensor
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.bathroom_presence

- alias: Aanwezigheid - Badkamer - Uit
  initial_state: off
  trigger:
    platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: "off"
    for:
      minutes: 6

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.bathroom_presence
