- alias: Aanwezigheid - Badkamer - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_door_bathroom_contact, binary_sensor.multi_01_movement
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.bathroom_presence

- alias: Aanwezigheid - Badkamer - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.multi_01_movement
    to: "off"
    for:
      minutes: 1

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.bathroom_presence
