- alias: Aanwezigheid - Badkamer - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_5_contact, binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor_3
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.bathroom_presence

- alias: Aanwezigheid - Badkamer - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor_3
    to: "off"
    for:
      minutes: 3

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.bathroom_presence
