- alias: Ventilation - Bathroom - On (number 2)
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_presence
      to: "on"
      for:
        minutes: 2

  action:
    - service: homeassistant.turn_on
      entity_id: script.bathroom_ventilation_10_minutes_on

- alias: Ventilation - Bathroom - On (humidity)
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_humidity_rising
      to: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: script.bathroom_ventilation_30_minutes_on
