- alias: Verlichting - Woonkamer - Uit
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_dark
      to: "off"
      for:
        minutes: 15

    - platform: state
      entity_id: input_boolean.livingroom_presence
      to: "off"

#    - plaform: state
#      entity_id: remote.livingroom
#      to: "off"
#        for:
#          minutes: 2

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: "on"

#      - condition: state
#        entity_id: remote.livingroom
#        state: "off"

      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.livingroom_presence
            state: "off"
          - condition: state
            entity_id: binary_sensor.livingroom_dark
            state: "off"
            for:
              minutes: 15

  action:
    - service: homeassistant.turn_on
      entity_id: scene.livingroom_lights_off
