- alias: Verlichting - Woonkamer - Uit
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_dark
      to: "off"
      for:
        minutes: 10

    - platform: state
      entity_id: binary_sensor.presence_sensor_fp2_4947_presence_sensor_1
      to: "off"
      for:
        minutes: 10

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: "on"

      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.presence_sensor_fp2_4947_presence_sensor_1
            state: "off"
            for:
              minutes: 10

          - condition: state
            entity_id: binary_sensor.livingroom_dark
            state: "off"
            for:
              minutes: 10

  action:
    - service: homeassistant.turn_on
      entity_id: scene.livingroom_lights_off
