- alias: Verlichting - Woonkamer - Normaal - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_contact_1_contact
        - binary_sensor.zigbee_occupancy_2_occupancy
        - binary_sensor.zigbee_occupancy_4_occupancy
        - binary_sensor.zigbee_occupancy_5_occupancy
        - input_boolean.livingroom_presence
        - input_boolean.livingroom_auto
      to: "on"

    - platform: state
      entity_id: binary_sensor.livingroom_dark
      to: "on"
      for:
        minutes: 1

    # - platform: state
    #   entity_id: binary_sensor.livingroom_tv_on
    #   to: "off"

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: "Normaal"

      - condition: state
        entity_id: input_boolean.livingroom_presence
        state: "on"

      - condition: state
        entity_id: binary_sensor.livingroom_dark
        state: "on"

      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: "on"

      # - condition: state
      #   entity_id: binary_sensor.livingroom_tv_on
      #   state: "off"

  action:
    - service: homeassistant.turn_on
      entity_id: scene.livingroom_lights_normal
