- alias: Verlichting - Woonkamer - Normaal - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.presence_sensor_fp2_4947_presence_sensor_1
        - input_boolean.livingroom_auto
      from: "off"
      to: "on"

    - platform: state
      entity_id: binary_sensor.livingroom_dark
      to: "on"
      for:
        minutes: 2

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.presence_sensor_fp2_4947_presence_sensor_1
        state: "on"

      - condition: state
        entity_id: input_select.house_mode
        state: "Normaal"

      - condition: state
        entity_id: binary_sensor.livingroom_dark
        state: "on"

      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: "on"

      - condition: template
        value_template: '{{ states("input_select.livingroom_scene") == "Uit" }}'

  action:
    - service: homeassistant.turn_on
      entity_id: scene.livingroom_lights_normal
