- alias: Lightning - Livingroom - Theater - On
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_tv_on
      to: "on"
      for:
        seconds: 30

    - platform: state
      # change of room-mode
      entity_id: input_boolean.livingroom_auto
      to: "on"

    - platform: state
      entity_id: binary_sensor.livingroom_dark
      to: "on"
      for:
        minutes: 3

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.livingroom_tv_on
        state: "on"
        for:
          seconds: 30

      - condition: state
        entity_id: binary_sensor.livingroom_dark
        state: "on"
        for:
          minutes: 3

      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: scene.livingroom_lights_night
