- alias: Test (on)
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_sensor_fp2_4947_presence_sensor_1
      to: "on"

  action:
    - service: light.turn_on
      entity_id: light.window_sill_01
      data:
        brightness: 8
        rgbw_color: [0, 0, 0, 255]
        effect: Solid

- alias: Test (off)
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_sensor_fp2_4947_presence_sensor_1
      to: "off"

  action:
    - service: light.turn_off
      entity_id: light.window_sill_01
