- platform: mqtt
  name: kitchen
  command_topic: "zigbee/kitchen_light/set"
  state_topic: "zigbee/kitchen_light/set"
  brightness: true
  schema: json

- platform: mqtt
  name: bedroom_sink
  command_topic: "zigbee/bedroom_sink/set"
  state_topic: "zigbee/bedroom_sink/set"
  brightness: true
  schema: json

- platform: mqtt
  name: workroom_light
  command_topic: "zigbee/workroom_light/set"
  state_topic: "zigbee/workroom_light/set"
  brightness: true
  color_temp: true
  schema: json
