- alias: Verlichting - Hal (beneden) - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_sensor_hallway_downstairs_occupancy
        - binary_sensor.zigbee_sensor_hallway_downstairs_coatrack_occupancy
        - binary_sensor.zigbee_sensor_entrance_occupancy
        - input_boolean.hallway_downstairs_presence
      to: "on"

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: "Normaal"
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.zigbee_sensor_hallway_downstairs_illuminance
            below: 30
          - condition: numeric_state
            entity_id: sensor.zigbee_sensor_hallway_downstairs_coatrack_illuminance
            below: 40

  action:
    - service: homeassistant.turn_on
      entity_id: light.shelly_dimmer_hallway_downstairs
      data:
        brightness_pct: 45

- alias: Verlichting - Hal (beneden) - Aan (Nacht)
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_sensor_hallway_downstairs_occupancy
        - binary_sensor.zigbee_sensor_hallway_downstairs_coatrack_occupancy
        - input_boolean.hallway_downstairs_presence
      to: "on"

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: "Nacht"
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.zigbee_sensor_hallway_downstairs_illuminance
            below: 30
          - condition: numeric_state
            entity_id: sensor.zigbee_sensor_hallway_downstairs_coatrack_illuminance
            below: 40

  action:
    - service: homeassistant.turn_on
      entity_id: light.shelly_dimmer_hallway_downstairs
      data:
        brightness_pct: 15

- alias: Verlichting - Hal (beneden) - Standby
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_downstairs_presence
      to: "off"

  condition:
    condition: state
    entity_id: light.shelly_dimmer_hallway_downstairs
    state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: light.shelly_dimmer_hallway_downstairs
      data:
        brightness_pct: 15

- alias: Verlichting - Hal (beneden) - Uit
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_downstairs_presence
      to: "off"
      for:
        minutes: 10

    - platform: numeric_state
      entity_id: sensor.zigbee_sensor_hallway_downstairs_illuminance
      above: 60
      for:
        minutes: 3

  action:
    - service: homeassistant.turn_off
      entity_id: light.shelly_dimmer_hallway_downstairs
