- alias: Aanwezigheid - Gang beneden - Aan
  trigger:
    - platform: state
      entity_id: group.hallway_downstairs_presence
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.hallway_downstairs_presence

- alias: Aanwezigheid - Gang beneden - Uit
  trigger:
    platform: state
    entity_id: group.hallway_downstairs_presence
    to: "off"
    for:
      minutes: 5

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.hallway_downstairs_presence
