- alias: Woonkamer - Scenes
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_select.livingroom_scene

  condition:
    condition: template
    value_template: "{{ trigger.to_state.state != 'Automatisch' }}"

  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.livingroom_scene", "Aan") %}
            scene.livingroom_lights_on
          {% elif is_state("input_select.livingroom_scene", "Normaal") %}
            scene.livingroom_lights_normal
          {% elif is_state("input_select.livingroom_scene", "Nacht") %}
            scene.livingroom_lights_night
          {% elif is_state("input_select.livingroom_scene", "Uit") %}
            scene.livingroom_lights_off
          {% endif %}
