log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  time_zone: Europe/Amsterdam
  latitude: 51.9225
  longitude: 4.47917
  elevation: 0
  plugins:
    HASS:
      type: hass
      ha_url: "https://home.ashwinvandijk.nl"
      token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI0ZjM2NzIzMDdiMzk0NTI3YjAzY2UzM2E0NDRlZjg1MyIsImlhdCI6MTU1OTEzMDA5OSwiZXhwIjoxODc0NDkwMDk5fQ.Flmdzjm-VaQeXkaH8J1U1D2YCso84lg39TCpPVc2t2g"
