logs:
appdaemon:
  time_zone: Europe/Amsterdam
  latitude: 51.9225
  longitude: 4.47917
  elevation: 0
  plugins:
    HASS:
      type: hass
      ha_url: "https://home.ashwinvandijk.nl"
      token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlOTRmNzA1MTAwMmY0OTk5YmMyZTdiMzQ5Mjc4MmViZCIsImlhdCI6MTU5MzYwNDI2OSwiZXhwIjoxOTA4OTY0MjY5fQ.oY_Pu5TkHQT-32c_RPCdADzpd4iQZTqsjBFeJSY5GNI"
