logs:
appdaemon:
  time_zone: Europe/Amsterdam
  latitude: 51.9225
  longitude: 4.47917
  elevation: 0
  plugins:
    HASS:
      type: hass
      ha_url: "https://home.ashwinvandijk.nl"
      token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjNGE0ZDZlNjM3YTU0M2VkOWY4NjNjZTczYWNiNDM4MyIsImlhdCI6MTU5MzYwNTkwNiwiZXhwIjoxOTA4OTY1OTA2fQ.zgme2O44jBgyJk0kXVfzyDQ4XhekTZE9NifjQB_tizU"
