logs:
appdaemon:
  time_zone: Europe/Amsterdam
  latitude: 51.9225
  longitude: 4.47917
  elevation: 0
  plugins:
    HASS:
      type: hass
      ha_url: "https://home.ashwinvandijk.nl"
      token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjNDFjYTRkMThlMDI0NTViYmUwNmFlYTBiYTU1YmI1NiIsImlhdCI6MTU5MzYwNjk5MiwiZXhwIjoxOTA4OTY2OTkyfQ.m00t5Bi_TbiFh0gJyOgHUSKKGKky_JPe-EmVaJUkUKo"
