- alias: Lightning - Washroom - On
  trigger:
    - platform: state
      entity_id: input_boolean.washroom_presence
      to: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: light.zigbee_e27c_4_light
      data:
        brightness: 255

- alias: Lightning - Washroom - Off
  trigger:
    - platform: state
      entity_id: input_boolean.washroom_presence
      to: "off"
      for:
        seconds: 5

  action:
    - service: homeassistant.turn_off
      entity_id: light.zigbee_e27c_4_light
