- alias: Verlichting - Washok - Aan
  trigger:
    - platform: state
      entity_id: input_boolean.washroom_presence
      to: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: light.zigbee_washroom_light
      data:
        brightness: 255
        kelvin: 2800

- alias: Verlichting - Washok - Uit
  trigger:
    - platform: state
      entity_id: input_boolean.washroom_presence
      to: "off"
      for:
        seconds: 3

  action:
    - service: homeassistant.turn_off
      entity_id: light.zigbee_washroom_light
