- alias: Lightning - Washroom - On
  trigger:
    - platform: state
      entity_id: input_boolean.washroom_presence
      to: "on"

  action:
    - service: light.turn_on
      entity_id: light.zigbee_e27_2_light
      data:
        brightness: 255

- alias: Lightning - Washroom - Off
  trigger:
    - platform: state
      entity_id: input_boolean.washroom_presence
      to: "off"

  action:
    - service: light.turn_off
      entity_id: light.zigbee_e27_2_light
