- alias: Aanwezigheid - Washok - Backup
  trigger:
    - platform: state
      entity_id: light.zigbee_e27c_4_light
      to: "on"
      for:
        minutes: 1

  action:
    service: light.turn_off
    entity_id: light.zigbee_e27c_4_light
