- alias: Presence - Washroom - On
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_3
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.washroom_presence

- alias: Presence - Washroom - Off
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_contact_3
    to: "off"
    for:
      seconds: 5

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.washroom_presence

- alias: Presence - Washroom - Fallback
  trigger:
    platform: state
    entity_id: input_boolean.washroom_presence
    to: "on"
    for:
      minutes: 10

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.washroom_presence
