- alias: Lightning - Bedroom - On
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_sensor_bedroom_occupancy, input_boolean.bedroom_presence
      to: "on"

    - platform: numeric_state
      entity_id: sensor.zigbee_sensor_hallway_upstairs_illuminance
      below: 80
      for:
        minutes: 1

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bedroom_in_bed
        state: "off"

      - condition: template
        value_template: "{{ states.input_select.house_mode.state != 'Nacht' }}"

      - condition: numeric_state
        entity_id: sensor.zigbee_occupancy_6_illuminance
        below: 80

  action:
    - service: homeassistant.turn_on
      entity_id: light.shelly_02

- alias: Lightning - Bedroom - Off
  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_presence
      to: "off"

    - platform: numeric_state
      entity_id: sensor.zigbee_occupancy_6_illuminance
      above: 70
      for:
        minutes: 3

  action:
    - service: homeassistant.turn_off
      entity_id: light.shelly_02
