- alias: Lightning - Bedroom - On
  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_presence
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bedroom_in_bed
        state: "off"

      - condition: template
        value_template: "{{ states.input_select.house_mode.state != 'Night' }}"

  action:
    - service: homeassistant.turn_on
      entity_id: light.shelly_05

- alias: Lightning - Bedroom - Off
  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_presence
      to: "off"

  action:
    - service: homeassistant.turn_off
      entity_id: light.shelly_05
