- alias: Media - Bedroom - Mute
  trigger:
    platform: template
    value_template: "{{state_attr('media_player.snapcast_client_slaapkamer', 'is_volume_muted') == True}}"
    for:
      seconds: 1

  action:
    service: switch.turn_off
    entity_id: switch.plug_bedroom_speakers_switch

- alias: Media - Bedroom - Unmute
  trigger:
    platform: template
    value_template: "{{state_attr('media_player.snapcast_client_slaapkamer', 'is_volume_muted') == False}}"

  action:
    service: switch.turn_on
    entity_id: switch.plug_bedroom_speakers_switch
