- alias: Aanwezigheid - Slaapkamer - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_2_contact, binary_sensor.zigbee_occupancy_6_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.bedroom_presence

- alias: Aanwezigheid - Slaapkamer - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_occupancy_6_occupancy
    to: "off"
    for:
      minutes: 5

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.bedroom_presence


- alias: Presence - Bedroom - Force off
  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_presence
      to: "off"
      for:
        hours: 6

      - service: script.turn_on
        entity_id: script.bedroom_off
