- alias: Aanwezigheid - Slaapkamer - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_occupancy_6_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.bedroom_presence

- alias: Aanwezigheid - Slaapkamer - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_occupancy_6_occupancy
    to: "off"
    for:
      minutes: 5

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.bedroom_presence
