- alias: Aanwezigheid - Slaapkamer - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_contact_2_contact, binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor_3
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.bedroom_presence

- alias: Aanwezigheid - Slaapkamer - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor_3
    to: "off"
    for:
      minutes: 15

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.bedroom_presence
