- id: wakeup_reset
  alias: "Wakeup Reset Time"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == ((states.input_datetime.wakeup_time.attributes.timestamp | int + 3600) | timestamp_custom('%H:%M', False)) }}" # Add 1 hour to the existing alarm for a time to setup the next one

  action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.wakeup_time
      data_template:
        time: >
          {% if now().isoweekday() == 6 %}
            {{ states('input_datetime.wakeup_default_sunday') }}
          {% elif states('binary_sensor.workday_tomorrow') == 'on' %}
            {{ states('input_datetime.wakeup_default_workday') }}
          {% else %}
            {{ states('input_datetime.wakeup_default_saturday_holiday') }}
          {% endif %}
    - service_template: input_boolean.turn_on
      data:
        entity_id: input_boolean.wakeup_enabled

- id: wakeup_routine
  alias: "Wakeup Routine"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.wakeup_enabled
      state: "on"
  action:
    - service: light.turn_on
      entity_id: light.bedroom_sink

    - service: notify.ios_ashwiphone
      data_template:
        title: "Alarm Clock"
        message: "Wakeup!"
        data:
          push:
            category: "alarmclock"
            badge: 0

- alias: "Wakeup Snooze"
  id: wakeup_snooze
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SNOOZE
  action:
    - service: light.turn_off
      entity_id: light.bedroom_sink

- alias: "Awake"
  id: wakeup_awake
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: AWAKE
  action: # Put the rest of your I'm awake routine in here
    - service: light.turn_on
      entity_id: light.bedroom_sink
