- alias: Verlichting - Werkkamer - Aan
  trigger:
    - platform: state
      entity_id: input_boolean.workroom_presence
      to: "on"

    - platform: numeric_state
      entity_id: sensor.zigbee_sensor_workroom_illuminance
      below: 250
      for:
        minutes: 1

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.workroom_presence
        state: "on"

      - condition: numeric_state
        entity_id: sensor.zigbee_sensor_workroom_illuminance
        below: 250

  action:
    - service: light.turn_on
      entity_id: light.shelly_dimmer_workroom
      data:
        brightness_pct: 75

- alias: Verlichting - Werkkamer - Standby
  trigger:
    - platform: state
      entity_id: input_boolean.workroom_presence
      to: "off"

    - platform: numeric_state
      entity_id: sensor.zigbee_sensor_workroom_illuminance
      above: 400
      for:
        minutes: 5

  condition:
    condition: state
    entity_id: light.shelly_dimmer_workroom
    state: "on"

  action:
    - service: light.turn_on
      entity_id: light.shelly_dimmer_workroom
      data:
        brightness_pct: 40

- alias: Verlichting - Werkkamer - Uit
  trigger:
    - platform: state
      entity_id: input_boolean.workroom_presence
      to: "off"
      for:
        minutes: 3

    - platform: numeric_state
      entity_id: sensor.zigbee_sensor_workroom_illuminance
      above: 400
      for:
        minutes: 10

  action:
    - service: light.turn_off
      entity_id: light.shelly_dimmer_workroom
