- alias: Aanwezigheid - Werkkamer - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy_workroom_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.workroom_presence

- alias: Aanwezigheid - Werkkamer - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.occupancy_workroom_occupancy
    to: "off"
    for:
      minutes: 3

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.workroom_presence
