- alias: Speech - SetLightOn
  trigger:
    platform: event
    event_type: rhasspy_SetLightOn
  action:
    - service: script.turn_on
      data_template:
        entity_id: "script.speech_{{trigger.event.data.room}}_lights_on"

- alias: Speech - SetLightOff
  trigger:
    platform: event
    event_type: rhasspy_SetLightOff
  action:
    - service: script.turn_on
      data_template:
        entity_id: "script.speech_{{trigger.event.data.room}}_lights_off"
