- alias: Speech - SetTemperature
  trigger:
    platform: event
    event_type: rhasspy_SetTemperature
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: "climate.{{trigger.event.data.room}}"
        temperature: "{{trigger.event.data.temperature}}"
    - service: notify.mobile_app_ashwiphone
      data_template:
        message: "{{trigger.event.data.room}} op {{trigger.event.data.temperature}} graden"

- alias: Speech - IncreaseTemperature
  trigger:
    platform: event
    event_type: rhasspy_IncreaseTemperature
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: "climate.{{trigger.event.data.room}}"
        temperature: "{{state_attr('climate.{{trigger.event.data.room}}', 'temperature') + 1 }}"
    - service: notify.mobile_app_ashwiphone
      data_template:
        message: "{{trigger.event.data.room}} op {{trigger.event.data.temperature}} graden"
