# --- Normal mode --- #
- alias: Lightning - Livingroom - On
  trigger:
    - platform: state
      entity_id: input_boolean.livingroom_presence
      to: "on"

    - platform: state
      # change of room-scene
      entity_id: input_select.livingroom_scene
      to: "Automatisch"

  # - platform: state
  #   entity_id: binary_sensor.livingroom_dark
  #   to: 'on'
  #   for:
  #     minutes: 3

  condition:
    condition: and
    conditions:
      # - condition: state
      #   entity_id: input_select.mode
      #   state: 'Normaal'

      # - condition: state
      #   entity_id: input_boolean.livingroom_presence
      #   state: "on"

      # - condition: state
      #   entity_id: binary_sensor.livingroom_dark
      #   state: 'on'
      #   for:
      #     minutes: 3

      - condition: state
        entity_id: input_select.livingroom_scene
        state: "Automatisch"

  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_lights_normal
