# --- Normal mode - ON --- #
- alias: Lightning - Livingroom - Normal - On
  trigger:
    - platform: state
      entity_id: input_boolean.livingroom_presence
      to: "on"

    - platform: state
      # change of room-mode
      entity_id: input_boolean.livingroom_auto
      to: "on"

    - platform: state
      entity_id: binary_sensor.livingroom_dark
      to: "on"
      for:
        minutes: 3

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: "Normaal"

      - condition: state
        entity_id: input_boolean.livingroom_presence
        state: "on"

      - condition: state
        entity_id: binary_sensor.livingroom_dark
        state: "on"
        for:
          minutes: 3

      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: scene.livingroom_lights_normal

# --- Night mode - ON --- #
- alias: Lightning - Livingroom - Night - On
  trigger:
    - platform: state
      entity_id: input_boolean.livingroom_presence
      to: "on"

    - platform: state
      # change of room-mode
      entity_id: input_boolean.livingroom_auto
      to: "on"

    - platform: state
      entity_id: binary_sensor.livingroom_dark
      to: "on"
      for:
        minutes: 3

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: "Nacht"

      - condition: state
        entity_id: input_boolean.livingroom_presence
        state: "on"

      - condition: state
        entity_id: binary_sensor.livingroom_dark
        state: "on"
        for:
          minutes: 3

      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: scene.livingroom_lights_night

# --- Global - OFF -- #
- alias: Lightning - Livingroom - Off
  trigger:
    - platform: state
      entity_id: input_boolean.livingroom_presence
      to: "off"

    - platform: state
      # change to automatic mode
      entity_id: input_boolean.livingroom_auto
      to: "on"

    - platform: state
      entity_id: binary_sensor.livingroom_dark
      to: "on"
      for:
        minutes: 3

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.livingroom_presence
        state: "on"

      - condition: state
        entity_id: binary_sensor.livingroom_dark
        state: "on"
        for:
          minutes: 3

      - condition: state
        entity_id: input_boolean.livingroom_auto
        state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: scene.livingroom_lights_off
