- alias: Aanwezigheid - Woonkamer - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_door_livingroom_contact
        - binary_sensor.zigbee_sensor_livingroom_fusebox_occupancy
        - binary_sensor.zigbee_sensor_livingroom_closet_occupancy
        - binary_sensor.zigbee_sensor_livingroom_tv_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.livingroom_presence

- alias: Aanwezigheid - Woonkamer - Uit
  trigger:
    platform: state
    entity_id: group.livingroom_presence
    to: "off"
    for:
      minutes: 10

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.livingroom_presence
