- alias: Aanwezigheid - Woonkamer - Aan
  trigger:
    - platform: state
      entity_id: group.livingroom_presence
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.livingroom_presence

- alias: Aanwezigheid - Woonkamer - Uit
  trigger:
    platform: state
    entity_id: group.livingroom_presence
    to: "off"
    for:
      minutes: 10

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.livingroom_presence
