- alias: Aanwezigheid - Woonkamer - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_contact_1_contact
        - binary_sensor.zigbee_occupancy_2_occupancy
        - binary_sensor.zigbee_occupancy_4_occupancy
        - binary_sensor.zigbee_occupancy_5_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.livingroom_presence

- alias: Aanwezigheid - Woonkamer - Uit
  trigger:
    platform: state
    entity_id: group.livingroom_presence
    to: "off"
    for:
      minutes: 10

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.livingroom_presence
