- alias: Woonkamer - Afstandsbediening
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_select.livingroom_remote

  action:
    - service: remote.turn_on
      data_template:
        entity_id: remote.livingroom
        activity: >
          {% if is_state("input_select.livingroom_remote", "PS4") %}
            PS4
          {% elif is_state("input_select.livingroom_remote", "Chromecast") %}
            Chromecast
          {% elif is_state("input_select.livingroom_remote", "Multiroom") %}
            Multiroom
          {% elif is_state("input_select.livingroom_remote", "Uit") %}
            PowerOff
          {% endif %}

- alias: Woonkamer - Afstandsbediening sync
  initial_state: "on"
  trigger:
    platform: state
    entity_id: sensor.livingroom_remote

  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.livingroom_remote
        option: >
          {% if is_state("sensor.livingroom_remote", "PS4") %}
            PS4
          {% elif is_state("sensor.livingroom_remote", "Chromecast") %}
            Chromecast
          {% elif is_state("sensor.livingroom_remote", "PowerOff") %}
            Uit
          {% endif %}

- alias: Woonkamer - Emulated Roku - Play-Pause
  trigger:
    - platform: event
      event_type: roku_command
      event_data:
        source_name: HASS
        type: keypress
        key: Play
  action:
    - service: media_player.media_play_pause
      entity_id: media_player.chromecast_livingroom

- alias: Woonkamer - Emulated Roku - Play-Pause
  trigger:
    - platform: event
      event_type: roku_command
      event_data:
        source_name: HASS
        type: keypress
        key: Sleep
  action:
    - service: media_player.media_stop
      entity_id: media_player.chromecast_livingroom
