- alias: Woonkamer - Afstandsbediening
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_select.livingroom_remote

  action:
    - service: remote.turn_on
      data_template:
        entity_id: "remote.livingroom"
        activity: >
          {% if is_state("input_select.livingroom_remote", "PS4") %}
            "PS4"
          {% elif is_state("input_select.livingroom_remote", "Chromecast") %}
            "Chromecast"
          {% elif is_state("input_select.livingroom_remote", "Uit") %}
            "PowerOff"
          {% endif %}

- alias: Woonkamer - Afstandsbediening sync
  initial_state: "on"
  trigger:
    platform: state
    entity_id: remote.livingroom

  action:
    - service: input_select.set_option
      data_template:
        entity_id: "input_select.livingroom.remote"
        option: >
          {% if is_state("input_select.livingroom_remote", "PS4") %}
            "PS4"
          {% elif is_state("input_select.livingroom_remote", "Chromecast") %}
            "Chromecast"
          {% elif is_state("input_select.livingroom_remote", "PowerOff") %}
            "Uit"
          {% endif %}
