- alias: Woonkamer - Scenes
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_select.livingroom_scene

  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.livingroom_scene", "Focus") %}
            scene.livingroom_lights_focus
          {% elif is_state("input_select.livingroom_scene", "Normaal") %}
            scene.livingroom_lights_normal
          {% elif is_state("input_select.livingroom_scene", "NYE") %}
            scene.livingroom_lights_nye
          {% elif is_state("input_select.livingroom_scene", "Gedimd") %}
            scene.livingroom_lights_dimmed
          {% elif is_state("input_select.livingroom_scene", "Chill") %}
            scene.livingroom_lights_chill
          {% elif is_state("input_select.livingroom_scene", "Uit") %}
            scene.livingroom_lights_off
          {% endif %}
