- alias: Lightning - Switch - Double
  trigger:
    platform: mqtt
    topic: shelly_01/double_click

  action:
    - service: homeassistant.turn_on
      entity_id: script.livingroom_off

- alias: Lightning - Switch - Triple
  trigger:
    platform: mqtt
    topic: shelly_01/triple_click

  action:
    - service: homeassistant.turn_on
      entity_id: scene.house_away
