- alias: Verlichting - Gang (boven) - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_sensor_hallway_upstairs_occupancy
        - input_boolean.hallway_upstairs_presence
      to: "on"

    - platform: numeric_state
      entity_id: sensor.zigbee_sensor_hallway_upstairs_illuminance
      below: 70

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.hallway_upstairs_presence
        state: "on"

      - condition: numeric_state
        entity_id: sensor.zigbee_sensor_hallway_upstairs_illuminance
        below: 70

  action:
    - service: homeassistant.turn_on
      entity_id: light.hallway_upstairs

- alias: Verlichting - Gang (boven) - Uit
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_upstairs_presence
      to: "off"

    - platform: numeric_state
      entity_id: sensor.zigbee_sensor_hallway_upstairs_illuminance
      above: 70
      for:
        minutes: 3

  action:
    - service: homeassistant.turn_off
      entity_id: light.hallway_upstairs

- alias: Verlichting - Dakterras
  trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/zigbee_button_terrace'
  condition:
    condition: template
    value_template: "{{ 'single' == trigger.payload_json.click }}"
  action:
    service: light.toggle
    entity_id: light.shelly_terrace_lights
