- alias: Verlichting - Gang (boven) - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_sensor_hallway_upstairs_occupancy
        - input_boolean.hallway_upstairs_presence
      to: "on"

    - platform: template
      value_template: "{{ state_attr('binary_sensor.binary_sensor.zigbee_sensor_hallway_upstairs_occupancy', 'Illuminance') < 700 }}"

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.hallway_upstairs_presence
        state: "on"

      - condition: template
        value_template: "{{ state_attr('binary_sensor.binary_sensor.zigbee_sensor_hallway_upstairs_occupancy', 'illuminance') < 700 }}"

      - condition: state
        entity_id: input_select.house_mode
        state: "Normaal"

  action:
    - service: light.turn_on
      entity_id: light.hallway_upstairs
      data:
        brightness_pct: 50

- alias: Verlichting - Gang (boven) - Aan - Nacht
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_sensor_hallway_upstairs_occupancy
        - input_boolean.hallway_upstairs_presence
      to: "on"

    - platform: template
      value_template: "{{ state_attr('binary_sensor.binary_sensor.zigbee_sensor_hallway_upstairs_occupancy', 'illuminance') < 700 }}"

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.hallway_upstairs_presence
        state: "on"

      - condition: template
        value_template: "{{ state_attr('binary_sensor.binary_sensor.zigbee_sensor_hallway_upstairs_occupancy', 'illuminance') < 700  }}"

      - condition: state
        entity_id: input_select.house_mode
        state: "Nacht"

  action:
    - service: light.turn_on
      entity_id: light.hallway_upstairs
      data:
        brightness_pct: 1

- alias: Verlichting - Gang (boven) - Uit
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_upstairs_presence
      to: "off"

    - platform: template
      value_template: "{{ state_attr('binary_sensor.binary_sensor.zigbee_sensor_hallway_upstairs_occupancy', 'illuminance') > 750 }}"
      for:
        minutes: 3

  action:
    - service: light.turn_off
      entity_id: light.hallway_upstairs

- alias: Verlichting - Dakterras
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/zigbee_button_terrace"
  condition:
    condition: template
    value_template: "{{ 'single' == trigger.payload_json.click }}"
  action:
    service: light.toggle
    entity_id: light.shelly_terrace_lights
