- alias: Verlichting - Gang (boven) - Aan
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_upstairs_presence
      to: "on"

  condition:
    condition: numeric_state
    entity_id: sensor.zigbee_occupancy_7_illuminance
    below: 70

  action:
    - service: homeassistant.turn_on
      entity_id: switch.sonoff_02

- alias: Verlichting - Gang (boven) - Uit
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_upstairs_presence
      to: "off"

    - platform: numeric_state
      entity_id: sensor.zigbee_occupancy_7_illuminance
      above: 70
      for:
        minutes: 3

  action:
    - service: homeassistant.turn_off
      entity_id: switch.sonoff_02
