- alias: Aanwezigheid - Gang (boven) - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_occupancy_7_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.hallway_upstairs_presence

- alias: Aanwezigheid - Slaapkamer - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_occupancy_7_occupancy
    to: "off"
    for:
      minutes: 10

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.hallway_upstairs_presence
