- alias: Aanwezigheid - Gang (boven) - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_sensor_hallway_upstairs_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.hallway_upstairs_presence

- alias: Aanwezigheid - Gang (boven) - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_sensor_hallway_upstairs_occupancy
    to: "off"
    for:
      minutes: 3

  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: "Normaal"

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.hallway_upstairs_presence

- alias: Aanwezigheid - Gang (boven) - Uit (Nacht)
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_sensor_hallway_upstairs_occupancy
    to: "off"

  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: "Nacht"

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.hallway_upstairs_presence
