- alias: Watering
  trigger:
    - platform: time
        at: '8:30:00'
    - platform: time
      at: '14:30:00'
    - platform: time
      at: '20:30:00'

  action:
  - service: homeassistant.turn_on
    entity_id: switch.plug_workroom_speakers_switch
  - delay: 00:00:30
  - service: homeassistant.turn_off
    entity_id: switch.plug_workroom_speakers_switch

