- alias: "Appliances - Kitchen - Dishwasher - Running"
  trigger:
    - platform: numeric_state
      entity_id: sensor.plug_01_power
      above: 5

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: "Draait"

- alias: "Appliances - Kitchen - Dishwasher - Done"
  trigger:
    - platform: numeric_state
      entity_id: sensor.plug_01_power
      below: 3
      for:
        minutes: 3

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: "Klaar"
