- alias: Verlichting - Keuken - Aan
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_sensor_kitchen_occupancy
        - input_boolean.kitchen_presence
      to: "on"

    - platform: template
      value_template: "{{ state_attr('sensor.zigbee_sensor_kitchen','illuminance') }}"
      below: 800

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: "Normaal"

      - condition: template
        value_template: "{{ state_attr('sensor.zigbee_sensor_kitchen','illuminance') }}"
        below: 800

      - condition: state
        entity_id: input_boolean.kitchen_presence
        state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchen
      data:
        brightness: 255
        transition: 1

- alias: Verlichting - Keuken - Aan (Nacht)
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.zigbee_sensor_kitchen_occupancy
        - input_boolean.kitchen_presence
      to: "on"

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: "Nacht"

      - condition: template
        value_template: "{{ state_attr('sensor.zigbee_sensor_kitchen','illuminance') }}"
        below: 800

  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchen
      data:
        brightness: 25
        transition: 1

- alias: Verlichting - Keuken - Standby
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_presence
      to: "off"

  condition:
    condition: state
    entity_id: light.kitchen
    state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchen
      data:
        brightness: 15
        transition: 30

- alias: Verlichting - Keuken - Uit
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_presence
      to: "off"
      for:
        minutes: 10

    - platform: template
      value_template: "{{ state_attr('sensor.zigbee_sensor_kitchen','illuminance')  }}"
      above: 820
      for:
        minutes: 4

  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchen
      data:
        transition: 30
