- alias: Lightning - Kitchen - On
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_presence
      to: "on"

  condition:
    condition: numeric_state
    entity_id: sensor.zigbee_occupancy_1_illuminance
    below: 50

  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchen
      data:
        brightness: 255
        transition: 1

- alias: Lightning - Kitchen - Standby
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_presence
      to: "off"

  condition:
    condition: state
    entity_id: light.kitchen
    state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchen
      data:
        brightness: 25
        transition: 15

- alias: Lightning - Kitchen - Off
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_presence
      to: "off"
      for:
        minutes: 5

    - platform: numeric_state
      entity_id: sensor.zigbee_occupancy_1_illuminance
      above: 50
      for:
        minutes: 3

  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchen
      data:
        transition: 5
