- alias: 'Kitchen - Media control'
  trigger:
    platform: mqtt
    topic: 'zigbee/zigbee_remote_01'
#  condition:
#    - condition: state
#      entity_id: light.bad_01
#      state: 'on'
  action:
    - service: media_player.volume_set
      entity_id: media_player.snapcast_client_keuken
      data_template:
        volume_level: >
          {% set remote = state_attr('sensor.zigbee_remote_01_action', 'brightness') | int %}
          {% set volume = state_attr('media_player.snapcast_client_keuken', 'volume_level') | int  %}
          {% set increment = 0.05  %}
          {% if remote > 245 %}
            {% if volume  < 1 %}
              {{ (volume + increment) }}
            {% else %}
              1
            {% endif %}
          {% else %}
            {% if volume  > 0.99 %}
              {{ ( (1 / increment) | round(0) * increment | int ) }}
            {% else %}
              {{ ( ((remote / increment) | round(0) * increment) | int ) }}
            {% endif %}
          {% endif %}
