- alias: Aanwezigheid - Keuken - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_sensor_kitchen_occupancy
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.kitchen_presence

- alias: Aanwezigheid - Keuken - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_sensor_kitchen_occupancy
    to: "off"
    for:
      minutes: 1

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.kitchen_presence
