- alias: House - Presence - On
  trigger:
    - platform: state
      entity_id: group.house_presence
      to: "on"

  action:
    - service: rest_command.tado_home

- alias: House - Presence - Off
  trigger:
    - platform: state
      entity_id: group.house_presence
      to: "off"

  action:
    - service: rest_command.tado_away
