- alias: House - Aanwezigheid - On
  trigger:
    - platform: state
      entity_id: group.house_presence
      to: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: script.house_home

- alias: House - Aanwezigheid - Off
  trigger:
    - platform: state
      entity_id: group.house_presence
      to: "off"
      for:
        minutes: 5

  action:
    - service: homeassistant.turn_on
      entity_id: script.house_off
