- alias: House - Presence - On
  trigger:
    - platform: state
      entity_id: group.house_presence
      to: "on"
  action:
    - service: homeassistant.turn_on
      entity_id: scene.house_home

- alias: House - Presence - Off
  trigger:
    - platform: state
      entity_id: group.house_presence
      to: "off"
      for:
        minutes: 10

  action:
    - service: homeassistant.turn_on
      entity_id: scene.house_away
