- platform: mqtt
  name: "airco_werkkamer"
  current_temperature_topic: "hisense_ac/f_temp_in/status"
  fan_mode_command_topic: "hisense_ac/t_fan_speed/command"
  fan_mode_state_topic: "hisense_ac/t_fan_speed/status"
  fan_modes:
    - "auto"
    - "lower"
    - "low"
    - "medium"
    - "high"
    - "higher"
  mode_command_topic: "hisense_ac/t_work_mode/command"
  mode_state_topic: "hisense_ac/t_work_mode/status"
  modes:
    - "fan_only"
    - "heat"
    - "cool"
    - "dry"
    - "auto"
  power_command_topic: "hisense_ac/t_power/command"
  power_state_topic: "hisense_ac/t_power/status"
  swing_mode_command_topic: "hisense_ac/t_fan_power/command"
  swing_mode_state_topic: "hisense_ac/t_fan_power/status"
  temperature_command_topic: "hisense_ac/t_temp/command"
  temperature_state_topic: "hisense_ac/t_temp/status"
  temperature_unit: "F"
  precision: 1.0
