- platform: template
  sensors:
    livingroom_remote:
      value_template: "{{ state_attr('remote.livingroom', 'current_activity') }}"

    livingroom_dark:
      value_template: "{{ ((states('sensor.zigbee_occupancy_2_illuminance') | float + states('sensor.zigbee_occupancy_4_illuminance') | float + states('sensor.zigbee_occupancy_5_illuminance') | float) / 3) | round() }}"

    tumbledryer_on_time:
      friendly_name: Starttijd
      value_template: >
          {% if is_state('input_select.tumbledryer_status', 'Draait') %}
            {{ state_attr('input_datetime.tumbledryer_start', 'timestamp') | timestamp_custom('%H:%M:%S', True) }}
          {% else %}
            ---
          {% endif %}


    washingmachine_on_time:
      friendly_name: Starttijd
      value_template: >
          {% if is_state('input_select.washingmachine_status', 'Draait') %}
            {{ state_attr('input_datetime.washingmachine_start', 'timestamp') | timestamp_custom('%H:%M:%S', True) }}
          {% else %}
            ---
          {% endif %}
