- platform: template
  sensors:
    tautulli_stream_count:
      friendly_name: "Streams"
      unit_of_measurement: "streams"
      value_template: "{{ state_attr('sensor.tautulli', 'stream_count') }}"

    tautulli_wan_bandwidth:
      friendly_name: "Bandbreedte"
      unit_of_measurement: ""
      value_template: "{{ state_attr('sensor.tautulli', 'wan_bandwidth') }}"

    livingroom_remote:
      value_template: "{{ state_attr('remote.livingroom', 'current_activity') }}"

    livingroom_dark:
      value_template: "{{ ((states('sensor.zigbee_occupancy_2_illuminance') | float + states('sensor.neo_coolcam_battery_powered_pir_sensor_luminance_3') | float + states('sensor.neo_coolcam_battery_powered_pir_sensor_luminance_4') | float) / 3) | round() | float }}"
