- platform: waze_travel_time
  name: ANWB naar Azaleastraat
  origin: zone.anwb
  destination: zone.home
  region: "EU"

- platform: waze_travel_time
  name: Azaleastraat naar ANWB
  origin: zone.home
  destination: zone.anwb
  region: "EU"

- platform: waze_travel_time
  name: Ashwin naar Azaleastraat
  origin: device_tracker.ashwiphone
  destination: zone.home
  region: "EU"
