- platform: waze_travel_time
  name: ANWB naar Ashwin's huis
  origin: zone.anwb
  destination: zone.home
  region: "EU"

- platform: waze_travel_time
  name: Ashwin's huis naar ANWB
  origin: zone.home
  destination: zone.anwb
  region: "EU"

- platform: waze_travel_time
  name: Ashwin naar Ashwin's huis
  origin: device_tracker.ashwiphone
  destination: zone.home
  region: "EU"

- platform: waze_travel_time
  name: Ashwin naar Lilian's huis
  origin: device_tracker.ashwiphone
  destination: zone.lilian
  region: "EU"
