- alias: Aanwezigheid - Inloopkast - Aan
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee_sensor_closet_occupancy
      from: "off"
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.closet_presence

- alias: Aanwezigheid - Inloopkast - Uit
  trigger:
    platform: state
    entity_id: binary_sensor.zigbee_sensor_closet_occupancy
    to: "off"
    for:
      seconds: 6

  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.closet_presence
