- alias: WLED outside - ON evening
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"

  action:
    service: light.turn_on
    entity_id: light.outside

- alias: WLED outside - OFF evening
  trigger:
    platform: time
    at: "23:45:00"

  action:
    service: light.turn_off
    entity_id: light.outside

- alias: WLED outside - ON morning
  trigger:
    platform: time
    at: "06:00:00"

  action:
    service: light.turn_on
    entity_id: light.outside

- alias: WLED outside - OFF morning
  trigger:
    platform: sun
    event: sunrise
    offset: "01:00:00"

  action:
    service: light.turn_off
    entity_id: light.outside


- alias: Deurbel - WLED outside
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell
      to: "on"

  condition:
    condition: state
    entity_id: light.outside
    state: "on"
  action:
    - service: scene.create
      data:
        scene_id: doorbell_wled_revert
        snapshot_entities: 'light.outside'
    - service: light.turn_on
      data:
        brightness: 255
        entity_id: light.outside
    - service: wled.effect
      entity_id: light.outside
      data:
        effect: 'Colorloop'
        speed: 225
    - delay: 00:00:15
    - service: scene.turn_on
      data:
        entity_id: scene.doorbell_wled_revert
    - service: wled.effect
      entity_id: light.christmas_tree
      data:
        speed: 90
