- alias: Tree outside - ON evening
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"

  action:
    service: switch.turn_on
    entity_id: switch.plug_tree_outside_switch

- alias: Tree outside - OFF evening
  trigger:
    platform: time
    at: "23:45:00"

  action:
    service: switch.turn_off
    entity_id: switch.plug_tree_outside_switch

- alias: Tree outside - ON morning
  trigger:
    platform: time
    at: "06:00:00"

  action:
    service: switch.turn_on
    entity_id: switch.plug_tree_outside_switch

- alias: Tree outside - OFF morning
  trigger:
    platform: sun
    event: sunrise
    offset: "01:00:00"

  action:
    service: switch.turn_off
    entity_id: switch.plug_tree_outside_switch
