- alias: Tree outside - ON evening
  trigger:
    platform: sun
    event: sunset
    offset: "-01:30:00"

  action:
    service: switch.turn_on
    entity_id: switch.plug_tree_outside_switch

- alias: Tree outside - OFF evening
  trigger:
    platform: time
    at: "00:30:00"

  action:
    service: switch.turn_off
    entity_id: switch.plug_tree_outside_switch

- alias: Tree outside - ON morning
  trigger:
    platform: time
    at: "05:30:00"

  action:
    service: switch.turn_on
    entity_id: switch.plug_tree_outside_switch

- alias: Tree outside - OFF morning
  trigger:
    platform: sun
    event: sunrise
    offset: "01:30:00"

  action:
    service: switch.turn_off
    entity_id: switch.plug_tree_outside_switch
