- alias: WLED christmas tree - ON evening
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"

  action:
    service: light.turn_on
    entity_id: light.christmas_tree

- alias: WLED christmas tree - OFF evening
  trigger:
    platform: time
    at: "23:30:00"

  action:
    service: light.turn_off
    entity_id: light.christmas_tree

- alias: Deurbel - WLED christmas tree
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell
      to: "on"

  condition:
    condition: state
    entity_id: light.christmas_tree
    state: "on"
  action:
    - service: scene.create
      data:
        scene_id: doorbell_wled_tree_revert
        snapshot_entities: 'light.christmas_tree'
    - service: light.turn_on
      data:
        brightness: 255
        entity_id: light.christmas_tree
    - service: wled.effect
      entity_id: light.christmas_tree
      data:
        effect: 'Colorloop'
        speed: 225
    - delay: 00:00:15
    - service: scene.turn_on
      data:
        speed: 70
        entity_id: scene.doorbell_wled_tree_revert
