input_boolean:
  symfonisk_volume:
    name: Symfonisk Volume
    initial: off
  symfonisk_dummy_delay:
  symfonisk_updown:
    name: Symfonisk up or down
    initial: off

script:
  symfonisk_lower_volume:
    sequence:
      - condition: state
        entity_id: input_boolean.symfonisk_volume
        state: 'on'

      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_dummy_delay

      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_dummy_delay

      - service: media_player.volume_set
        entity_id: media_player.snapcast_client_keuken
        data_template:
          volume_level: '{{ states.media_player.snapcast_client_keuken.attributes.volume_level - 0.01 }}'

      - service: script.turn_off
        entity_id: script.symfonisk_lower_volume

      - service: script.turn_on
        entity_id: script.symfonisk_lower_volume

  symfonisk_raise_volume:
    sequence:

      - condition: state
        entity_id: input_boolean.symfonisk_volume
        state: 'off'

      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_dummy_delay

      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_dummy_delay

      - service: media_player.volume_set
        entity_id: media_player.snapcast_client_keuken
        data_template:
          volume_level: '{{ states.media_player.snapcast_client_keuken.attributes.volume_level + 0.01 }}'

      - service: script.turn_off
        entity_id: script.symfonisk_raise_volume

      - service: script.turn_on
        entity_id: script.symfonisk_raise_volume

automation:
  - alias: symfonisk skip forward
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'skip_forward' in trigger.payload }}"
    action:
      - service: media_player.media_next_track
        entity_id: media_player.snapcast_client_keuken

  - alias: symfonisk skip backward
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'skip_backward' in trigger.payload }}"
    action:
      - service: media_player.media_previous_track
        entity_id: media_player.snapcast_client_keuken

  - alias: symfonisk play/pause
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'play_pause' in trigger.payload }}"
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.snapcast_client_keuken

  - alias: symfonisk raise volume on
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'rotate_right' in trigger.payload }}"

    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_volume
      - service: script.turn_on
        entity_id: script.symfonisk_raise_volume
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_updown

  - alias: symfonisk raise volume off
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'rotate_stop' in trigger.payload }}"
      - condition: state
        entity_id: input_boolean.symfonisk_updown
        state: 'off'

    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_volume

  - alias: symfonisk lower volume on
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'rotate_left' in trigger.payload }}"

    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_volume
      - service: script.turn_on
        entity_id: script.symfonisk_lower_volume
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_updown

  - alias: symfonisk lower volume off
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'rotate_stop' in trigger.payload }}"
      - condition: state
        entity_id: input_boolean.symfonisk_updown
        state: 'on'

    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_volume
