
automation:
  - alias: symfonisk skip forward
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee2mqtt/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'skip_forward' in trigger.payload }}"
    action:
      - service: media_player.media_next_track
        entity_id: media_player.spotify_ashwin_van_dijk

  - alias: symfonisk skip backward
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee2mqtt/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'skip_backward' in trigger.payload }}"
    action:
      - service: media_player.media_previous_track
        entity_id: media_player.spotify_ashwin_van_dijk

  - alias: symfonisk play/pause
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: 'zigbee2mqtt/zigbee_remote_01'
    condition:
      - condition: template
        value_template: "{{ 'play_pause' in trigger.payload }}"
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.spotify_ashwin_van_dijk
